export const SOLICITUD_PRESTAMO_SOLICITANTE_SECURITY_DEF = {
  readAccess: 'SOLICITUD_PRESTAMO_SOLICITANTE_READ',
  updateAccess: 'SOLICITUD_PRESTAMO_SOLICITANTE_UPDATE',
  createAccess: 'SOLICITUD_PRESTAMO_SOLICITANTE_CREATE',
  deleteAccess: 'SOLICITUD_PRESTAMO_SOLICITANTE_DELETE'
};
