export const LIMITES_INVERSIONISTA_SECURITY_DEF = {
  readAccess: 'LIMITES_INVERSIONISTA_READ',
  updateAccess: 'LIMITES_INVERSIONISTA_UPDATE',
  createAccess: 'LIMITES_INVERSIONISTA_CREATE',
  deleteAccess: 'LIMITES_INVERSIONISTA_DELETE'
};
