export const BOLETIN_CONTENIDO_SECURITY_DEF = {
  readAccess: 'BOLETIN_CONTENIDO_READ',
  updateAccess: 'BOLETIN_CONTENIDO_UPDATE',
  createAccess: 'BOLETIN_CONTENIDO_CREATE',
  deleteAccess: 'BOLETIN_CONTENIDO_DELETE'
};
