export const AULA_SOLICITUD_FINALIZADA_SECURITY_DEF = {
  readAccess: 'AULA_SOLICITUD_FINALIZADA_READ',
  updateAccess: 'AULA_SOLICITUD_FINALIZADA_UPDATE',
  createAccess: 'AULA_SOLICITUD_FINALIZADA_CREATE',
  deleteAccess: 'AULA_SOLICITUD_FINALIZADA_DELETE'
};
